language: php

php:
  - 7.2.1

before_script:
  - cp .env.travis .env
  - cp phpunit.xml-travis phpunit.xml
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - mysql -e 'create database homestead_test;'
  - php artisan key:generate
  - php artisan migrate
  - php artisan passport:install

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - cat storage/logs/

cache:
  directories:
    - vendor
